name = "EOptInterface"
uuid = "96d9f51d-8c41-4e2d-b1a3-7b48dea3ddd1"
version = "0.1.0"
authors = ["Joseph Choi <jsphchoi@mit.edu>", "Dimitri Alston <dimitri.alston@uconn.edu>", "Matthew Stuber <matthew.stuber@uconn.edu>"]

[deps]
Ipopt = "b6b21f68-93f8-5de0-b562-5493be1d77c9"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
ModelingToolkit = "961ee093-0014-501f-94e3-6117800e7a78"

[compat]
Ipopt = "1.11.0"
JuMP = "1"
ModelingToolkit = "10"
julia = "1.12"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
